### ISSUE TITLE
`Hashable` doesn't build on Mac M1 for GHC 9.0.2

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#260]
Marco is now getting the following problem when trying to install on Mac M1 with GHC 9.0.2:
```
Failed to build hashable-1.4.1.0.
Build log (
/Users/marcocasadio/.cabal/logs/ghc-9.0.2/hshbl-1.4.1.0-865f38d3.log ):
Configuring library for hashable-1.4.1.0..
Preprocessing library for hashable-1.4.1.0..
Building library for hashable-1.4.1.0..
[1 of 7] Compiling Data.Hashable.Imports ( src/Data/Hashable/Imports.hs, dist/build/Data/Hashable/Imports.o, dist/build/Data/Hashable/Imports.dyn_o )
[2 of 7] Compiling Data.Hashable.LowLevel ( src/Data/Hashable/LowLevel.hs, dist/build/Data/Hashable/LowLevel.o, dist/build/Data/Hashable/LowLevel.dyn_o )

In file included from /var/folders/9_/9l6qz02n6yz4qlgqvdfr1f500000gn/T/ghc9908_0/ghc_20.c:4:0: error:
    

In file included from /Users/marcocasadio/.ghcup/ghc/9.0.2/lib/ghc-9.0.2/lib/../lib/aarch64-osx-ghc-9.0.2/rts-1.0.2/include/ffi.h:66:0: error:
    

/Users/marcocasadio/.ghcup/ghc/9.0.2/lib/ghc-9.0.2/lib/../lib/aarch64-osx-ghc-9.0.2/rts-1.0.2/include/ffitarget.h:6:10: error:
     fatal error: 'ffitarget_arm64.h' file not found
  |
6 | #include "ffitarget_arm64.h"
  |          ^
#include "ffitarget_arm64.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Failed to build hashable-1.4.1.0 (which is required by
exe:vehicle-new-golden-test from vehicle-0.1.0 and exe:vehicle from
vehicle-0.1.0). See the build log above for details.
```

This [GHC issue](https://gitlab.haskell.org/ghc/ghc/-/issues/20592) suggests that this was fixed in GHC 9.2.3 (or maybe alternatively by adding `--ghc-option=(pkg-config --cflags libffi)` to the build/install commands).

@wenkokke as the build system expert, what's the best course of action? See if the option above works and add a conditional stanza to the `.cabal` file?

**Comment by wenkokke** [comment]
I’d suggest documenting this, and asking users on M1 to include the output of 
```sh
echo "$(xcrun --show-sdk-path)/usr/include/ffi"
```
to their `cabal.project.local` file as [`extra-include-dirs`](https://cabal.readthedocs.io/en/3.4/cabal-project.html#cfg-field-extra-include-dirs).

If it is a predictable path, we could include it conditionally on OS and architecture, but I’m afraid it isn’t.

**Comment by wenkokke** [comment]
This should be fixed when [this](https://github.com/libffi/libffi/pull/621) merges, or we’ll see another 9.0 release.

@MatthewDaggitt You could reopen that as an issue for 9.0.2?

**Comment by wenkokke** [comment]
If there's a static configuration option that works, we can put it in cabal.project using [conditionals on OS, architecture, and GHC version](https://cabal.readthedocs.io/en/3.8/cabal-package.html#conditions). Perhaps there's a way we could sneak a pkg-config dependency into hashable?

**Comment by wenkokke** [comment]
I'll say this is fixed with GHC 9.2 and 9.4 support?
