### PR TITLE
Support for GHC 9.2

### PR DESCRIPTION
**Pull request by wenkokke**
Pull request for work on support for GHC 9.2.

### CODE REVIEW

**Comment by wenkokke** [comment]
@MatthewDaggitt The build fails with:
```
src/Vehicle/Compile/Type/Monad/Class.hs:284:7: error: 
    [-Wincomplete-uni-patterns, -Werror=incomplete-uni-patterns]
Error:     Pattern match(es) are non-exhaustive
    In a pattern binding:
        Patterns of type ‘([MetaInfo], [MetaInfo])’ not matched:
            ([], [])
            ((_:_), [])
    |
284 |   let (xs, info : ys) = splitAt metaIndex metaInfo
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build vehicle-0.1.0 (which is required by exe:vehicle
from vehicle-0.1.0).
```
Presumably, there were bugs in warnings-as-errors in previous versions of GHC?

**Comment by MatthewDaggitt** [comment]
Okay, hopefully have fixed :crossed_fingers:
